import { readFile, writeFile, readdir, mkdir, copyFile } from 'node:fs/promises'
import sharp from 'sharp'
import subsetFont from 'subset-font'

await mkdir('src/assets/fonts', { recursive: true })
await mkdir('src/assets/images/mobile', { recursive: true })
await sharp('public/logo.png').resize(32, 32, { fit: 'inside' }).png().toFile('public/favicon.png')

// Keep all Pulang glyphs; only change the font container, not the typeface.
await writeFile('src/assets/fonts/pulang.woff2', await subsetFont(await readFile('public/Pulang.ttf'), undefined, { targetFormat: 'woff2', keepAllGlyphs: true }))
for (const weight of [400, 500, 600, 700]) {
  await copyFile(`node_modules/@fontsource/poppins/files/poppins-latin-${weight}-normal.woff2`, `src/assets/fonts/poppins-latin-${weight}.woff2`)
}
await copyFile('node_modules/@fontsource/poppins/LICENSE', 'src/assets/fonts/Poppins-LICENSE.txt')
await copyFile('public/More Info.txt', 'src/assets/fonts/Pulang-LICENSE.txt')
await copyFile('node_modules/boxicons/LICENSE', 'src/assets/fonts/Boxicons-LICENSE.txt')

// Generate the exact existing Boxicons glyphs used in templates and JS bindings.
const files = await readdir('src', { recursive: true })
const source = (await Promise.all(files.filter(file => /\.(vue|js)$/.test(file)).map(file => readFile(`src/${file}`, 'utf8')))).join('\n')
const used = new Set(source.match(/\bbx[sl]?-[a-z0-9-]+\b/g))
const css = await readFile('node_modules/boxicons/css/boxicons.css', 'utf8')
const glyphs = [...css.matchAll(/\.([\w-]+):before\s*\{\s*content:\s*['"]\\([a-f0-9]+)['"];?\s*\}/g)].filter(match => used.has(match[1]))
if (!glyphs.length) throw new Error('No Boxicons glyphs found')
await writeFile('src/assets/fonts/boxicons-subset.woff2', await subsetFont(await readFile('node_modules/boxicons/fonts/boxicons.ttf'), glyphs.map(match => String.fromCodePoint(parseInt(match[2], 16))).join(''), { targetFormat: 'woff2' }))
const base = css.slice(css.indexOf('.bx\n'), css.search(/\.[\w-]+:before\s*\{/)).trim()
await writeFile('src/assets/boxicons.css', `/* Generated by npm run assets:optimize. Retains the original icon shapes. */\n@font-face { font-family: 'boxicons'; font-weight: normal; font-style: normal; font-display: swap; src: url('./fonts/boxicons-subset.woff2') format('woff2'); }\n${base}\n${glyphs.map(match => match[0]).join('\n')}\n`)

// Mobile variants preserve the crop/aspect ratio. Desktop still uses the originals.
for (const name of ['naskot', 'tumpeng', 'tumini', 'prasmanan', 'testi1', 'testi2']) {
  await sharp(`src/assets/images/${name}.webp`).resize({ width: 768, withoutEnlargement: true }).webp({ quality: 78 }).toFile(`src/assets/images/mobile/${name}.webp`)
}
await sharp('src/assets/images/banner.jpg').resize({ width: 768, withoutEnlargement: true }).webp({ quality: 78 }).toFile('src/assets/images/mobile/banner.webp')
console.log(`Prepared local fonts, ${glyphs.length} icons and 7 mobile images.`)
